/**
 * ⚠️ NOT NEEDED ANYMORE — replaced by task.feature.ts (createFeature version).
 * Every selector below is now auto-generated by createFeature:
 *   selectTasksState   → tasksFeature.selectTasksState (was created here manually)
 *   selectAllTasks     → tasksFeature.selectTasks      (auto, from the field name)
 *   selectTasksLoading → tasksFeature.selectLoading    (auto, from the field name)
 *   selectCompletedCount → moved to task.feature.ts    (computed — still manual)
 * Kept only for comparison/learning — safe to delete once you're comfortable.
 */
import { createFeatureSelector, createSelector } from '@ngrx/store';
import { TasksState, TASKS_FEATURE_KEY } from './task.reducer';

/**
 * SELECTORS = read-only queries into the store.
 * Components use these instead of owning the data themselves.
 * Derived values (like a completed count) are computed here, once,
 * instead of being duplicated inside every component.
 */
const selectTasksState = createFeatureSelector<TasksState>(TASKS_FEATURE_KEY);

export const selectAllTasks = createSelector(
  selectTasksState,
  (state) => state.tasks
);

export const selectTasksLoading = createSelector(
  selectTasksState,
  (state) => state.loading
);

export const selectCompletedCount = createSelector(
  selectAllTasks,
  (tasks) => tasks.filter((t) => t.completed).length
);
